packages:
  - 'apps/*'
  - 'packages/*'

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
  - esbuild
  - onnxruntime-node
  - protobufjs
  - sharp
  - msgpackr-extract
  - '@node-rs/argon2'
