import {
  areSkillsRelated,
  buildPagination,
  EDUCATION_LEVELS,
  extractKnownSkills,
  normalizeSkill,
  totalExperienceYears,
  type CandidateDashboardDto,
  type CandidateDetailDto,
  type CandidateListItemDto,
  type CandidateProfileDto,
  type CandidateSearchQuery,
  type EducationLevel,
  type Paginated,
  type ReplaceEducationInput,
  type ReplaceExperienceInput,
  type ReplaceSkillsInput,
  type UpdateCandidateProfileInput,
  replaceEducationSchema,
  replaceExperienceSchema,
  replaceSkillsSchema,
} from '@hireflow/shared';
import type { Prisma, PrismaClient } from '@hireflow/database';
import type { AIService } from '../ai/ai-service';
import { ForbiddenError, NotFoundError } from '../lib/errors';
import type { JobDispatcher } from '../jobs/definitions';
import {
  toApplicationListItemDto,
  toCandidateApplicationDto,
  toCandidateInterviewDto,
  toCandidateProfileDto,
  toInterviewDto,
  toPublicJobDto,
  toResumeDto,
  profileCompleteness,
} from '../mappers';
import {
  applicationListInclude,
  candidateApplicationInclude,
  candidateProfileInclude,
  interviewInclude,
  publicJobInclude,
  type CandidateProfileFull,
} from '../repositories/includes';
import type { VectorRepository } from '../repositories/vector.repository';
import type { Actor } from '../types/context';
import type { AuditService } from './audit.service';

const listSelect = {
  id: true,
  headline: true,
  currentRole: true,
  location: true,
  totalExperience: true,
  createdAt: true,
  user: { select: { firstName: true, lastName: true, email: true } },
  skills: {
    select: { skill: true, normalizedSkill: true, yearsExperience: true },
    orderBy: { yearsExperience: { sort: 'desc' as const, nulls: 'last' as const } },
  },
  experiences: { select: { title: true, company: true, description: true }, take: 5 },
} satisfies Prisma.CandidateProfileSelect;
type ListRow = Prisma.CandidateProfileGetPayload<{ select: typeof listSelect }>;

function maxEducation(levels: Array<EducationLevel | null>): EducationLevel | null {
  const ranks = levels.filter((l): l is EducationLevel => l !== null).map((l) => EDUCATION_LEVELS.indexOf(l));
  return ranks.length ? EDUCATION_LEVELS[Math.max(...ranks)]! : null;
}

/**
 * Reasons a candidate matched a semantic query, derived from their data: shared skills and
 * experience entries that mention query terms. Never generated by a model.
 */
export function explainSearchHit(query: string, row: Pick<ListRow, 'skills' | 'experiences' | 'totalExperience'>): string[] {
  const reasons: string[] = [];
  const querySkills = new Set(extractKnownSkills(query).map((s) => s.key));
  const shared = row.skills.filter((s) => querySkills.has(s.normalizedSkill));
  if (shared.length) {
    reasons.push(
      `Has ${shared.map((s) => (s.yearsExperience ? `${s.skill} (${s.yearsExperience} yrs)` : s.skill)).join(', ')}.`,
    );
  }
  const related = row.skills.filter(
    (s) => !querySkills.has(s.normalizedSkill) && [...querySkills].some((q) => areSkillsRelated(q, s.normalizedSkill)),
  );
  if (related.length) reasons.push(`Related experience: ${related.map((s) => s.skill).join(', ')}.`);
  const terms = query
    .toLowerCase()
    .split(/[^a-z0-9+#.]+/)
    .filter((t) => t.length > 3 && !['with', 'experience', 'strong', 'candidates', 'developer', 'engineer', 'that', 'have'].includes(t));
  const relevant = row.experiences.find((e) => terms.some((t) => `${e.title} ${e.description ?? ''}`.toLowerCase().includes(t)));
  if (relevant) reasons.push(`Relevant experience as ${relevant.title} at ${relevant.company}.`);
  if (row.totalExperience) reasons.push(`${row.totalExperience} years of total experience.`);
  return reasons;
}

export class CandidateService {
  constructor(
    private readonly prisma: PrismaClient,
    private readonly ai: AIService,
    private readonly vectors: VectorRepository,
    private readonly audit: AuditService,
    private readonly dispatcher: JobDispatcher,
  ) {}

  // ── Candidate self-service ────────────────────────────────────────────────

  private async loadByUser(userId: string): Promise<CandidateProfileFull> {
    const profile = await this.prisma.candidateProfile.findUnique({ where: { userId }, include: candidateProfileInclude });
    if (!profile) throw new ForbiddenError('Only candidates have a candidate profile');
    return profile;
  }

  async getOwn(userId: string): Promise<CandidateProfileDto> {
    return toCandidateProfileDto(await this.loadByUser(userId));
  }

  private async afterProfileChange(candidateId: string): Promise<void> {
    await this.dispatcher.dispatch('embedding.candidate', { candidateId }, { jobId: `embed-candidate-${candidateId}-${Date.now()}` });
  }

  async updateOwn(userId: string, input: UpdateCandidateProfileInput): Promise<CandidateProfileDto> {
    const profile = await this.loadByUser(userId);
    const data = Object.fromEntries(Object.entries(input).filter(([, v]) => v !== undefined));
    await this.prisma.candidateProfile.update({ where: { id: profile.id }, data });
    await this.afterProfileChange(profile.id);
    return this.getOwn(userId);
  }

  async replaceSkills(userId: string, raw: ReplaceSkillsInput): Promise<CandidateProfileDto> {
    const input = replaceSkillsSchema.parse(raw);
    const profile = await this.loadByUser(userId);
    const existing = new Map(profile.skills.map((s) => [s.normalizedSkill, s]));
    const seen = new Set<string>();
    const rows: Prisma.CandidateSkillCreateManyInput[] = [];
    for (const item of input.skills) {
      const normalized = normalizeSkill(item.skill);
      if (!normalized || seen.has(normalized.key)) continue;
      seen.add(normalized.key);
      const previous = existing.get(normalized.key);
      const unchanged =
        previous?.source === 'RESUME' &&
        previous.yearsExperience === item.yearsExperience &&
        previous.proficiency === item.proficiency;
      rows.push({
        candidateId: profile.id,
        skill: normalized.known ? normalized.name : item.skill,
        normalizedSkill: normalized.key,
        proficiency: item.proficiency,
        yearsExperience: item.yearsExperience,
        source: unchanged ? 'RESUME' : 'MANUAL',
      });
    }
    await this.prisma.$transaction([
      this.prisma.candidateSkill.deleteMany({ where: { candidateId: profile.id } }),
      this.prisma.candidateSkill.createMany({ data: rows }),
    ]);
    await this.afterProfileChange(profile.id);
    return this.getOwn(userId);
  }

  async replaceExperience(userId: string, raw: ReplaceExperienceInput): Promise<CandidateProfileDto> {
    const input = replaceExperienceSchema.parse(raw);
    const profile = await this.loadByUser(userId);
    const years = totalExperienceYears(input.experiences);
    await this.prisma.$transaction([
      this.prisma.workExperience.deleteMany({ where: { candidateId: profile.id } }),
      this.prisma.workExperience.createMany({
        data: input.experiences.map((e) => ({
          candidateId: profile.id,
          company: e.company,
          title: e.title,
          description: e.description ?? null,
          startDate: e.startDate,
          endDate: e.current ? null : e.endDate,
          current: e.current,
          source: 'MANUAL' as const,
        })),
      }),
      this.prisma.candidateProfile.update({
        where: { id: profile.id },
        data: {
          totalExperience: years > 0 ? years : null,
          currentRole: input.experiences.find((e) => e.current)?.title ?? profile.currentRole,
        },
      }),
    ]);
    await this.afterProfileChange(profile.id);
    return this.getOwn(userId);
  }

  async replaceEducation(userId: string, raw: ReplaceEducationInput): Promise<CandidateProfileDto> {
    const input = replaceEducationSchema.parse(raw);
    const profile = await this.loadByUser(userId);
    await this.prisma.$transaction([
      this.prisma.education.deleteMany({ where: { candidateId: profile.id } }),
      this.prisma.education.createMany({
        data: input.education.map((e) => ({
          candidateId: profile.id,
          institution: e.institution,
          degree: e.degree ?? null,
          field: e.field ?? null,
          level: e.level,
          startDate: e.startDate,
          endDate: e.endDate,
          grade: e.grade ?? null,
          source: 'MANUAL' as const,
        })),
      }),
      this.prisma.candidateProfile.update({
        where: { id: profile.id },
        data: { highestEducation: maxEducation(input.education.map((e) => e.level)) },
      }),
    ]);
    await this.afterProfileChange(profile.id);
    return this.getOwn(userId);
  }

  async dashboard(userId: string): Promise<CandidateDashboardDto> {
    const profile = await this.loadByUser(userId);
    const [applications, interviews, recommendations] = await Promise.all([
      this.prisma.application.findMany({
        where: { candidateId: profile.id },
        include: candidateApplicationInclude,
        orderBy: { updatedAt: 'desc' },
      }),
      this.prisma.interview.findMany({
        where: { application: { candidateId: profile.id }, status: 'SCHEDULED', scheduledAt: { gte: new Date() } },
        include: interviewInclude,
        orderBy: { scheduledAt: 'asc' },
        take: 5,
      }),
      this.vectors.recommendJobs(profile.id, 4),
    ]);

    let recommendedJobs: CandidateDashboardDto['recommendedJobs'] = [];
    if (recommendations.length) {
      const jobs = await this.prisma.job.findMany({ where: { id: { in: recommendations.map((r) => r.jobId) } }, include: publicJobInclude });
      const byId = new Map(jobs.map((j) => [j.id, j]));
      recommendedJobs = recommendations.flatMap((r) => {
        const job = byId.get(r.jobId);
        return job ? [{ ...toPublicJobDto(job), similarity: Math.round(r.similarity * 100) / 100 }] : [];
      });
    } else {
      const latest = await this.prisma.job.findMany({
        where: { status: 'PUBLISHED', applications: { none: { candidateId: profile.id } } },
        include: publicJobInclude,
        orderBy: { publishedAt: 'desc' },
        take: 4,
      });
      recommendedJobs = latest.map((job) => ({ ...toPublicJobDto(job), similarity: null }));
    }

    const active = applications.filter((a) => !['REJECTED', 'WITHDRAWN', 'HIRED'].includes(a.status));
    const primary = profile.resumes.find((r) => r.isPrimary) ?? profile.resumes[0] ?? null;
    return {
      profileCompleteness: profileCompleteness(profile),
      applications: {
        total: applications.length,
        active: active.length,
        interviews: applications.filter((a) => a.status === 'INTERVIEW').length,
        offers: applications.filter((a) => a.status === 'OFFER' || a.status === 'HIRED').length,
      },
      recentApplications: applications.slice(0, 5).map(toCandidateApplicationDto),
      upcomingInterviews: interviews.map(toCandidateInterviewDto),
      primaryResume: primary ? toResumeDto(primary) : null,
      recommendedJobs,
    };
  }

  // ── Recruiter views ───────────────────────────────────────────────────────

  private async latestApplications(organizationId: string, candidateIds: string[]) {
    const apps = await this.prisma.application.findMany({
      where: { candidateId: { in: candidateIds }, job: { organizationId } },
      select: {
        id: true,
        candidateId: true,
        status: true,
        appliedAt: true,
        job: { select: { id: true, title: true } },
        match: { select: { overallScore: true } },
      },
      orderBy: { appliedAt: 'desc' },
    });
    const latest = new Map<string, (typeof apps)[number]>();
    const counts = new Map<string, number>();
    for (const app of apps) {
      if (!latest.has(app.candidateId)) latest.set(app.candidateId, app);
      counts.set(app.candidateId, (counts.get(app.candidateId) ?? 0) + 1);
    }
    return { latest, counts };
  }

  private toListItem(
    row: ListRow,
    apps: Awaited<ReturnType<CandidateService['latestApplications']>>,
    similarity: number | null,
    reasons: string[],
  ): CandidateListItemDto {
    const latest = apps.latest.get(row.id);
    return {
      id: row.id,
      firstName: row.user.firstName,
      lastName: row.user.lastName,
      email: row.user.email,
      headline: row.headline,
      currentRole: row.currentRole,
      location: row.location,
      totalExperience: row.totalExperience,
      topSkills: row.skills.slice(0, 6).map((s) => s.skill),
      applicationCount: apps.counts.get(row.id) ?? 0,
      latestApplication: latest
        ? {
            id: latest.id,
            jobId: latest.job.id,
            jobTitle: latest.job.title,
            status: latest.status,
            overallScore: latest.match?.overallScore ?? null,
            appliedAt: latest.appliedAt.toISOString(),
          }
        : null,
      similarity: similarity === null ? null : Math.round(similarity * 1000) / 1000,
      matchReasons: reasons,
      createdAt: row.createdAt.toISOString(),
    };
  }

  /**
   * Hybrid candidate search. With `q`: embed the query, rank by vector similarity inside the
   * structured filters (single SQL statement), and explain each hit from its data. Without `q`:
   * a filtered, sorted listing. Only candidates who applied to this organization are visible.
   */
  async search(organizationId: string, query: CandidateSearchQuery): Promise<Paginated<CandidateListItemDto>> {
    const skills = (query.skills ?? []).map((s) => normalizeSkill(s)?.key).filter((k): k is string => !!k);
    const offset = (query.page - 1) * query.pageSize;

    if (query.q) {
      const vector = await this.ai.embedQuery(query.q);
      const { hits, total } = await this.vectors.searchCandidates(
        vector,
        {
          organizationId,
          skills,
          ...(query.minExperience !== undefined ? { minExperience: query.minExperience } : {}),
          ...(query.maxExperience !== undefined ? { maxExperience: query.maxExperience } : {}),
          ...(query.location ? { location: query.location.replace(/[%_\\]/g, '\\$&') } : {}),
          ...(query.jobId ? { jobId: query.jobId } : {}),
          ...(query.status?.length ? { statuses: query.status } : {}),
        },
        query.pageSize,
        offset,
      );
      const ids = hits.map((h) => h.candidateId);
      const [rows, apps] = await Promise.all([
        this.prisma.candidateProfile.findMany({ where: { id: { in: ids } }, select: listSelect }),
        this.latestApplications(organizationId, ids),
      ]);
      const byId = new Map(rows.map((r) => [r.id, r]));
      const items = hits.flatMap((hit) => {
        const row = byId.get(hit.candidateId);
        return row ? [this.toListItem(row, apps, hit.similarity, explainSearchHit(query.q!, row))] : [];
      });
      return { items, pagination: buildPagination(query.page, query.pageSize, total) };
    }

    const applicationFilter: Prisma.ApplicationWhereInput = {
      job: { organizationId },
      ...(query.jobId ? { jobId: query.jobId } : {}),
      ...(query.status?.length ? { status: { in: query.status } } : {}),
    };
    const where: Prisma.CandidateProfileWhereInput = {
      applications: { some: applicationFilter },
      ...(skills.length ? { AND: skills.map((key) => ({ skills: { some: { normalizedSkill: key } } })) } : {}),
      ...(query.minExperience !== undefined || query.maxExperience !== undefined
        ? {
            totalExperience: {
              ...(query.minExperience !== undefined ? { gte: query.minExperience } : {}),
              ...(query.maxExperience !== undefined ? { lte: query.maxExperience } : {}),
            },
          }
        : {}),
      ...(query.location ? { location: { contains: query.location, mode: 'insensitive' } } : {}),
    };
    const orderBy: Prisma.CandidateProfileOrderByWithRelationInput =
      query.sort === 'experience'
        ? { totalExperience: { sort: 'desc', nulls: 'last' } }
        : query.sort === 'name'
          ? { user: { firstName: 'asc' } }
          : { createdAt: 'desc' };

    const [total, rows] = await this.prisma.$transaction([
      this.prisma.candidateProfile.count({ where }),
      this.prisma.candidateProfile.findMany({ where, select: listSelect, orderBy, skip: offset, take: query.pageSize }),
    ]);
    const apps = await this.latestApplications(organizationId, rows.map((r) => r.id));
    return {
      items: rows.map((row) => this.toListItem(row, apps, null, [])),
      pagination: buildPagination(query.page, query.pageSize, total),
    };
  }

  /** Full candidate view for recruiters. Visible only when the candidate applied to this org. */
  async getForRecruiter(actor: Actor, candidateId: string): Promise<CandidateDetailDto> {
    const profile = await this.prisma.candidateProfile.findFirst({
      where: { id: candidateId, applications: { some: { job: { organizationId: actor.organizationId } } } },
      include: candidateProfileInclude,
    });
    if (!profile) throw new NotFoundError('Candidate');

    const [applications, interviews] = await Promise.all([
      this.prisma.application.findMany({
        where: { candidateId, job: { organizationId: actor.organizationId } },
        include: applicationListInclude,
        orderBy: { appliedAt: 'desc' },
      }),
      this.prisma.interview.findMany({
        where: { application: { candidateId, job: { organizationId: actor.organizationId } } },
        include: interviewInclude,
        orderBy: { scheduledAt: 'desc' },
      }),
    ]);

    await this.audit.recordQuietly(actor, { action: 'CANDIDATE_VIEWED', entityType: 'Candidate', entityId: candidateId });
    return {
      profile: toCandidateProfileDto(profile),
      applications: applications.map(toApplicationListItemDto),
      interviews: interviews.map(toInterviewDto),
    };
  }
}
